### ISSUE TITLE
Memory leak with GIDPUSH

### ISSUE THREAD

**Issue by abhishek1982** [TamarLabs/ReDe#19]
https://github.com/TamarLabs/ReDe/blob/811add560d4ee819168615e7b389f37ccd856841/src/module.c#L80

There seems to be a memory leak when using GIDPUSH with Redis 5.0.1 and jemalloc-5.1.0. 

We are implementing a timer-based game in which we need to submit entries to a dehydrator which expire in 15 minutes and after expiration, the same number of entries need to be submitted for the next round. When we submit about 20 entries at a time, Redis memory spikes by 35 Mb. This happens every 15 minutes and eventually, Redis goes OOM.

The memory spike was not found when we replaced GIDPUSH with PUSH by generating our own id, hence submitting this issue.

Few SOF links :
https://stackoverflow.com/questions/322938/recommended-way-to-initialize-srand

Abhishek

**Comment by daTokenizer** [comment]
seems to be fixed by 0f3adea , the issue was more than bad init of the srand seed, but the lack of freeing all the created tmp IDs that were created by the collisions

feel free to reopen if you still find this an issue.

@abhishek1982  THANK YOU FOR REPORTING!
