### ISSUE TITLE
Support for reliable messages with streams

### ISSUE THREAD

**Issue by kak-tus** [TamarLabs/ReDe#21]
I want to process delayed messages with fault tolerance garanties.
POLL command can't do that - it removes message after getting it.
And there is no command to get expired messages without removing them, to remove it later manually.

In redis 5 there is Streams - they can be used for this purpose, they have XACK command.
Message can be getted from REDE and moved to stream.

I can do this with some lua script in transaction. But it is not userfriendly.
Is it possible to add command like "REDE.XPOLL dehydrator_name stream_name", that can do this?

**Comment by daTokenizer** [comment]
better late than never, you can follow along with the dev branch on `feature/peek` where I will soon add the tests for xpoll and xack as per your request

**Comment by daTokenizer** [comment]
@kak-tus please migrate to v0.5.0 for the new commands
